export type {
  LocalizedText,
  ResumeEducationItem,
  ResumeExperienceItem,
  ResumeHighlightItem,
  ResumeLocale,
  ResumeProfile,
  ResumeProfileHero,
  ResumeProfileInterestItem,
  ResumeProfileLink,
  ResumeProjectItem,
  ResumePublishedSnapshot,
  ResumeSkillGroup,
  StandardResume,
} from '@my-resume/api-client';
