import {
  LocalizedText,
  ResumeEducationItem,
  ResumeExperienceItem,
  ResumeLocale,
  ResumeProjectItem,
} from '../../lib/published-resume-types';

export function readLocalizedText(
  value: LocalizedText,
  locale: ResumeLocale,
): string {
  return value[locale];
}

export function formatPeriod(
  item: ResumeProjectItem | ResumeExperienceItem | ResumeEducationItem,
): string {
  return `${item.startDate} - ${item.endDate}`;
}

export function formatPublishedAt(
  publishedAt: string,
  locale: ResumeLocale,
): string {
  return new Date(publishedAt).toLocaleString(
    locale === 'zh' ? 'zh-CN' : 'en-US',
    {
      hour12: false,
    },
  );
}

export const resumeLabels = {
  zh: {
    resumeNav: '简历',
    profileNav: '履历概览',
    aiTalkNav: 'AI Talk',
    themeLight: 'Light',
    themeDark: 'Dark',
    pageEyebrow: '公开简历',
    pageTitle: '给招聘方直接阅读的公开简历',
    pageDescription: '保留最核心的履历内容、导出入口与双语切换，让阅读路径直接、清晰、可验证。',
    standardEditionEyebrow: '当前版本',
    standardEditionTitle: '标准双语公开版',
    standardEditionDescription:
      '当前只维护一份可公开展示的标准简历，草稿保存与公开发布继续分离。',
    heroPrimaryAction: '进入履历概览',
    heroSecondaryAction: '查看 AI Talk',
    resumeSignalsEyebrow: '履历信号',
    resumeSignalsTitle: '公开简历速览',
    experienceCountLabel: '职业经历',
    experienceCountDescription: '段可追踪的核心职业经历。',
    projectsCountLabel: '代表项目',
    projectsCountDescription: '个沉淀到公开版里的代表项目。',
    skillsCountLabel: '技能分组',
    skillsCountDescription: '组便于阅读与导出的技能结构。',
    publicationStateLabel: '发布状态',
    publicationStateValue: '已发布',
    publicationStateDescription: '公开站当前正在读取最近一次手动发布版本。',
    emptyTitle: '当前还没有已发布的公开简历内容。',
    emptyDescription:
      '请先通过后台更新草稿并执行发布动作，公开站才会读取到最新已发布版本。',
    publishedAt: '已发布于',
    exportMarkdown: '导出 Markdown',
    exportPdf: '导出 PDF',
    experienceEyebrow: '工作经历',
    experienceTitle: '职业经历',
    experienceDescription: '聚焦过往公司的职责范围、业务场景与关键成果。',
    projectsEyebrow: '项目经历',
    projectsTitle: '代表项目',
    projectsDescription: '按标准模型展示项目背景、职责、亮点与技术栈。',
    educationEyebrow: '教育经历',
    educationTitle: '教育背景',
    educationDescription: '保留稳定学历信息，避免和项目型内容混排。',
    skillsEyebrow: '技能清单',
    skillsTitle: '技能结构',
    skillsDescription: '按类别聚合技术关键词，便于后续主题化展示。',
    highlightsEyebrow: '亮点',
    highlightsTitle: '补充亮点',
    highlightsDescription: '沉淀个人项目、开源参与与团队建设等补充信息。',
    interestsEyebrow: '兴趣方向',
    interestsTitle: '个人兴趣',
    profileEyebrow: 'about / profile',
    profileTitle: '公开履历概览',
    profileDescription: '这里放统计、公开链接、补充背景和后续面试时更适合被追问的上下文，不打断简历主阅读流。',
    profileStoryEyebrow: '候选人快照',
    aiTalkEyebrow: 'ai talk',
    aiTalkCardTitle: '个人知识库问答入口',
    aiTalkCardDescription: '后续这里会接入 RAG，对招聘方常见问题做更结构化、更可解释的回答。',
    aiTalkEnter: '进入 AI Talk',
    aiTalkTitle: 'AI Talk 占位入口',
    aiTalkDescription: '后续将基于已发布简历、博客与知识库素材，回答招聘方关于项目、经历、技术取舍与成长路径的问题。',
    aiTalkStatus: '即将接入 RAG',
    aiTalkReadyEyebrow: '当前阶段',
    aiTalkReadyTitle: '本轮先把入口与语义立住',
    aiTalkReadyLineOne: '当前页面先不接真实问答接口，只把公开站的信息架构和后续能力边界明确下来。',
    aiTalkReadyLineTwo: '未来会把已发布简历、公开博客与知识库素材作为检索上下文，保证回答来源可追溯。',
    aiTalkReadyLineThree: '等 RAG 能力接入后，这里会补充提问输入区、回答卡片、来源片段与反馈动作。',
    aiTalkPromptsEyebrow: '示例问题',
    aiTalkPromptsTitle: '未来可回答的问题方向',
  },
  en: {
    resumeNav: 'Resume',
    profileNav: 'Profile',
    aiTalkNav: 'AI Talk',
    themeLight: 'Light',
    themeDark: 'Dark',
    pageEyebrow: 'Published Resume',
    pageTitle: 'A public resume page built for direct recruiter reading',
    pageDescription: 'Keeps the most important resume content, bilingual switching, and export actions in one direct reading flow.',
    standardEditionEyebrow: 'Edition',
    standardEditionTitle: 'Standard Bilingual Edition',
    standardEditionDescription:
      'The project currently maintains one public standard resume while draft editing and publication stay separated.',
    heroPrimaryAction: 'Open Profile Overview',
    heroSecondaryAction: 'Visit AI Talk',
    resumeSignalsEyebrow: 'Reading Signals',
    resumeSignalsTitle: 'Public Resume Overview',
    experienceCountLabel: 'Experience',
    experienceCountDescription: 'core work chapters currently on the public page.',
    projectsCountLabel: 'Projects',
    projectsCountDescription: 'selected builds carried into the standard edition.',
    skillsCountLabel: 'Skill Groups',
    skillsCountDescription: 'structured groups ready for reading and export.',
    publicationStateLabel: 'Release State',
    publicationStateValue: 'Published',
    publicationStateDescription:
      'The public site is reading the most recent manually published snapshot.',
    emptyTitle: 'There is no published resume content yet.',
    emptyDescription:
      'Please update the draft and publish it from the admin dashboard before the public site can read the latest version.',
    publishedAt: 'Published at',
    exportMarkdown: 'Export Markdown',
    exportPdf: 'Export PDF',
    experienceEyebrow: 'Experience',
    experienceTitle: 'Work Experience',
    experienceDescription:
      'Highlights company scope, responsibilities, delivery context, and key outcomes.',
    projectsEyebrow: 'Projects',
    projectsTitle: 'Selected Projects',
    projectsDescription:
      'Shows project background, role, highlights, and technology stack from the standard model.',
    educationEyebrow: 'Education',
    educationTitle: 'Education',
    educationDescription:
      'Keeps stable academic information separated from project-focused content.',
    skillsEyebrow: 'Skills',
    skillsTitle: 'Skill Structure',
    skillsDescription:
      'Groups technical keywords by category for future theme and template expansion.',
    highlightsEyebrow: 'Highlights',
    highlightsTitle: 'Additional Highlights',
    highlightsDescription:
      'Captures personal projects, open-source work, and team-building achievements.',
    interestsEyebrow: 'Interests',
    interestsTitle: 'Personal Interests',
    profileEyebrow: 'about / profile',
    profileTitle: 'Public Profile Overview',
    profileDescription: 'This page carries signal cards, public links, and supporting context that should not interrupt the main resume reading flow.',
    profileStoryEyebrow: 'Candidate Snapshot',
    aiTalkEyebrow: 'ai talk',
    aiTalkCardTitle: 'Personal Knowledge Base Entry',
    aiTalkCardDescription: 'This will later host a RAG-powered Q&A surface for recruiter-facing questions.',
    aiTalkEnter: 'Open AI Talk',
    aiTalkTitle: 'AI Talk Placeholder',
    aiTalkDescription: 'Later this page will answer recruiter questions from the published resume, public blogs, and curated knowledge materials.',
    aiTalkStatus: 'RAG coming soon',
    aiTalkReadyEyebrow: 'Current Stage',
    aiTalkReadyTitle: 'The entry and product meaning come first',
    aiTalkReadyLineOne: 'This round does not wire up the real Q&A backend yet. It only establishes the public-site entry and future capability boundary.',
    aiTalkReadyLineTwo: 'The next step will use the published resume, public blogs, and knowledge materials as retrieval context.',
    aiTalkReadyLineThree: 'Once the RAG flow is ready, this page will grow an input area, answer cards, cited source snippets, and feedback actions.',
    aiTalkPromptsEyebrow: 'Prompt Direction',
    aiTalkPromptsTitle: 'Questions it should answer later',
  },
} as const;
